### PR TITLE
Implement methods for adding and removing host configurations

### PR DESCRIPTION
**Pull request by rbywater**
This commit adds the ability to programatically add and remove host
configurations.

### CODE REVIEW

**Comment by eddyhub** [comment]
Hi, I was wondering if anyone had a chance to take a look at this? Is there a chance this commit will be merged any time soon?

**Comment by rbywater** [comment]
I've asked on the mailing list a while back and got no response. So, unless someone else jumps in first, I'll look at doing at merging this PR and doing a new release soon myself.

**Comment by eddyhub** [comment]
I need this commit for a puppet module and was about to add the necessary methods myself but a check of the pull requests revealed, that you did it already. So if I can help getting the changes to a new release just tell me.

**Comment by rbywater** [comment]
Just release 1.13 so hopefully that will flow through soon with this change in. (Note I had a few issues so hopefully it does come through properly!)

**Pull request merged**
