### PR TITLE
feature/rework

### PR DESCRIPTION
**Pull request by phreakadelle**
I am using this plugin every day and most of our CI/CD jobs are relying on it.

Therefore i've spend some work to fix some of the most urgent issues. Now the plugin uses the Credentials (StandardUsername*Password / BasicSSHAuthentication).
Beside that i've added some validation for the Hostnames and added some (not all) permission checks.

The work is not yet done, but as this is a working version i wanted to raise this DRAFT PR.

### CODE REVIEW

**Review by timja — COMMENTED** [review]
To start with I would suggest reverting all the whitespace changes. None of the spaces to tabs changes, (and the other ones too, they can be in a separate PR if needed)

**Comment by gmcdonald** [comment]
Yes please, if possible lets leave out the reformatting so we can review the actual needed changes.
Thanks for working on this!

**Comment by phreakadelle** [comment]
Is there any formatting template I can use? That would be easy. 

I have no clue how to revert the formatting.

Further I need to consolidate the commits and squash them. So some work to do but I thought it would be helpful for a lot of people to see that things are moving.

**Comment by timja** [comment]
> Is there any formatting template I can use? That would be easy.
> 
> I have no clue how to revert the formatting.
> 
> Further I need to consolidate the commits and squash them. So some work to do but I thought it would be helpful for a lot of people to see that things are moving.

Generally best to leave format alone in functional PRs, google java format is used with the spotless-maven-plugin in a few repoes e.g GitHub-branch-source plugi

**Comment by phreakadelle** [comment]
Today i've tried to fix some of the tests but i am struggling, as my knowledge is very limited when it comes to UnitTests + Jenkins. Maybe you can give some advice... The Test "BapSshHostConfigurationTest" is testing if some methods with some expected parameters are getting called. 

To achieve a succesful testresult i need to mock the Credentials somehow. So i have to store/prepare some credentials but how and where should i do it? Do i need to create a credentials.xml file and put it somewhere? If this is already documented somewhere, please appologies.

**Comment by timja** [comment]
> To achieve a succesful testresult i need to mock the Credentials somehow. So i have to store/prepare some credentials but how and where should i do it? Do i need to create a credentials.xml file and put it somewhere? If this is already documented somewhere, please appologies.

Avoid mocking as much as possible with Jenkins, often difficult to get right.

This is in an integration test as you have a `JenkinsRule` there.

You should just be able to add credentials to the built in system provider, something like:
https://github.com/jenkinsci/slack-plugin/blob/e66d183873775b03eeb6b84428d8e7630e0f2c3d/src/test/java/jenkins/plugins/slack/pipeline/SlackUserIdsFromCommittersStepIntegrationTest.java#L31-L33

**Comment by gmcdonald** [comment]
@phreakadelle - how is the testing going? Do you need any more information/pointers?

**Comment by phreakadelle** [comment]
At the moment I have no time to work on it. I will be able to continue the work end of this month.

**Comment by gmcdonald** [comment]
Thanks for your time on this, we managed to fix the security issues another way.
You are welcome to create PRs for any other issues you find.

**Pull request closed without merging**
