### PR TITLE
Fix:SSH Key Path not taking from the Job param

### PR DESCRIPTION
**Pull request by ashu16815**
SSH Key path was not taken from job param value. Now its working fine, SSH Key Path can be job param as well.

### CODE REVIEW

**Comment by ashu16815** [comment]
Hi,

Request to maintainer to merge in main branch, So that folks can use it.

Cheers,
Ankit

**Comment by slide** [comment]
Close and reopen for build.

**Comment by ashu16815** [comment]
I think all check passed now, request you to merge this

**Comment by slide** [comment]
Can you remove some of the newlines you added? There is no need to add 3 newlines before and 3 after.

**Comment by ashu16815** [comment]
As suggested  : Its Done , extra Line removed

**Comment by ashu16815** [comment]
Thanks Alot Alex Ear

**Pull request merged**
