### PR TITLE
escape javascript the server name

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### CODE REVIEW

**Comment by daniel-beck** [comment]
This roughly doubles the number of escape characters on each round-trip of the global configuration form.
`foobar'` -> `foobar\'` -> `foobar\\\'` -> `foobar\\\\\\\'`

Not a security issue, just a bug IMO.

**Comment by olamy** [comment]
Agree but why would you use a quote here? 😀

**Comment by daniel-beck** [comment]
True, what kind of weirdo would name a computer something like _Daniel's MacBook Pro_?

**Comment by olamy** [comment]
> True, what kind of weirdo would name a computer something like _Daniel's MacBook Pro_?

correct! 
personally I would never trust pushing over ssh and using my personal keys to a server with such name!!

**Comment by derline** [comment]
> > True, what kind of weirdo would name a computer something like _Daniel's MacBook Pro_?
> 
> correct! personally I would never trust pushing over ssh and using my personal keys to a server with such name!! anyway I have removed this escaping #61
> 
> but you should note there are some validations on the name added 11yo ago [4280f00](https://github.com/jenkinsci/publish-over-ssh-plugin/commit/4280f009a59f48358fb527d251bb3b70a510e23b) which warn about using some characters `Cannot contain < & ' " \` that's coming from using a common validation for all `publish-over-` plugins and it's defined here https://github.com/jenkinsci/publish-over-plugin/blob/8857c829c4dec430aa945dec3bbb50df2be02b0d/src/main/java/jenkins/plugins/publish_over/BPValidators.java#L47 anyway this validation doesn't prevent to do it which is very useless...

When saving Chinese characters，it will become unicode characters with "\"，and warn about "Cannot contain < & ' " \".

**Pull request merged**
